version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:rw,cached  # Critical Windows flags
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    command: ["sh", "-c", "chown -R www-data:www-data /var/www/html && apache2-foreground"]