version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: krishighor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db

volumes:
  postgres_data: