version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    build: 
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: krishighor_postgres
    environment:
      POSTGRES_DB: krishighor
      POSTGRES_USER: krishighor_user
      POSTGRES_PASSWORD: krishighor_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - krishighor_network
    restart: unless-stopped

  # PHP-FPM Application
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krishighor_php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - krishighor_network
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=krishighor
      - DB_USER=krishighor_user
      - DB_PASS=krishighor_pass
    restart: unless-stopped

  # Nginx Web Server
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: krishighor_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - krishighor_network
    depends_on:
      - php
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  krishighor_network:
    driver: bridge
